language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:  
  - yarn run lint
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: public
  fqdn: glossario.opendevufcg.org
  on:
    branch: master
